### ISSUE TITLE
update ffmpeg to 2.5

### ISSUE THREAD

**Issue by lukasz-madon** [shunjikonishi/heroku-buildpack-ffmpeg#6]
I'd like to update the buildpack to 2.5 ffmpeg. How did you compile/get binaries? Thx. 

I'm trying to do the following.
- Download source 

```
~ $ DOWNLOAD_URL="https://ffmpeg.org/releases/ffmpeg-2.5.tar.gz"
~ $ curl -L --silent $DOWNLOAD_URL | tar xz
```
- Compile with the same configure as local

```
cd ffmpeg-2.5/
./configure --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --arch=x86_64 --enable-runtime-cpudetect
```
- Copy file from the server
  just copy binaries to static and download

There is a problem with compilation step

```
./configure
yasm/nasm not found or too old. Use --disable-yasm for a crippled build.
```

**Comment by shunjikonishi** [comment]
Maybe you have to compile binary on heroku dynos.  
I've built ffmpeg by according to following script.

https://gist.github.com/coopermaruyama/3963576

But valucan is already deprecated.
I don't know the modern way to how to compile binaries.

**Comment by lukasz-madon** [comment]
Thx @shunjikonishi I have used `heroku run`. At first I built a buildpack that will compile once and then I'll download with http, but uploading to s3 was more convenient. 

https://discussion.heroku.com/t/opencv-and-statically-compiled-python/105/2
https://github.com/lukasz-madon/heroku-buildpack-ffmpeg
